# Generated by Django 2.1.7 on 2019-04-20 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_sns', '0002_auto_20190417_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('user_id', models.IntegerField(default=0)),
                ('password', models.CharField(max_length=10)),
                ('mail_address', models.CharField(max_length=100)),
            ],
        ),
    ]
