# Generated by Django 2.1.7 on 2019-04-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_sns', '0003_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=10),
        ),
    ]
